name: Deploy Azure Function - Telemetry to Event Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Azure CLI
        uses: azure/setup-azure-cli@v1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Install dependencies
        run: |
          cd cloud-backend/send_telemetry
          pip install -r requirements.txt --target="./.python_packages/lib/site-packages"

      - name: Deploy to Azure Function App
        run: |
          cd cloud-backend/send_telemetry
          func azure functionapp publish ${{ secrets.FUNCTION_APP_NAME }} --python

